version: '3.8'

services: 
  web:
    build: .
    image: dj-img:1.0.0
    container_name: 'web-con'
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/app/
    ports: 
      - 8000:8000
    env_file: 
      - ./.env
    depends_on: 
      - db

  db:
    image: postgres:13.4-buster
    container_name: 'postgres-con'
    env_file: 
      - ./.env.db
    volumes: 
      - ./db/:/var/lib/postgresql/data 
    ports: 
      - 5432:5432