version: '3.9'

services: 
  web:
    build: .
    container_name: 'web-con'
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/code
    ports: 
      - '8000:8000'
    depends_on: 
      - db

  db:
    image: postgres
    container_name: 'postgres-con'
    env_file: .env.prod
    environment: 
      - POSTGRES_DB=DB_NAME
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASSWORD
    volumes: 
      - postgres_data:/var/lib/postgresql/data 

volumes: 
  postgres_data: